import {
  SIGN_UP,
  GET_PARTICIPANT,
  LOOKUP_PARTICIPANTS,
  HANDLE_PARTICIPANTS_RESPONSE,
  HANDLE_PARTICIPANT_RESPONSE,
  GET_PARTICIPANT_MESSAGES,
  HANDLE_PARTICIPANT_MESSAGES,
  SEND_PARTICIPANT_MESSAGE,
  HANDLE_SEND_PARTICIPANT_MESSAGE,
  SELECT_PARTICIPANT_MESSAGE,
  HANDLE_SELECT_PARTICIPANT_MESSAGE,
  GET_ANNOUNCEMENTS,
  HANDLE_ANNOUNCEMENTS,
} from './actionTypes';
import { createActions } from 'redux-actions';

/**
 * Participant related actions.
 */
const participantActions = createActions(
  SIGN_UP,
  GET_PARTICIPANT,
  HANDLE_PARTICIPANT_RESPONSE,
  GET_PARTICIPANT_MESSAGES,
  HANDLE_PARTICIPANT_MESSAGES,
  SEND_PARTICIPANT_MESSAGE,
  HANDLE_SEND_PARTICIPANT_MESSAGE,
  LOOKUP_PARTICIPANTS,
  HANDLE_PARTICIPANTS_RESPONSE,
  GET_ANNOUNCEMENTS,
  HANDLE_ANNOUNCEMENTS,
  SELECT_PARTICIPANT_MESSAGE,
  HANDLE_SELECT_PARTICIPANT_MESSAGE,
);

module.exports = participantActions;
